export const categoryArr = [
    {
        title:'杂记',
        cate:'1001',
        className:'circle-mid'
    },
    {
        title:'C#',
        cate:'1002',
        className:'circle-mid'
    },
    {
        title:'JavaScript',
        cate:'1004',
        className:'circle-mid'
    },
    {
        title:'VUE',
        cate:'1005',
        className:'circle-min'
    },
    {
        title:'.Net Core',
        cate:'1006',
        className:'circle-mid'
    },
    {
        title:'Linux',
        cate:'1007',
        className:'circle-min'
    },
    {
        title:'开发工具',
        cate:'1008',
        className:'circle-mid'
    },
    {
        title:'MongoDB',
        cate:'1010',
        className:'circle-mid'
    },
    {
        title:'ES',
        cate:'1011',
        className:'circle-mid'
    },
    {
        title:'Sql',
        cate:'1013',
        className:'circle-min'
    },
]


export var article = [
    {
        title:'CEFSharp如何打开多标签并管理多标签',
        cate:'1002',
        cateName:'c#',
        date:'2020-09-07',
        url:'/page/2020/cef_mutilTab.html'
    },
    {
        title:'日志',
        cate:'1001',
        cateName:'杂记',
        date:'2020-10-06',
        url:'/log.html'
    },
    {
        title:'前言',
        cate:'1001',
        cateName:'杂记',
        date:'2020-10-06',
        url:'/hello.html'
    },
    {
        title:'JS小问题汇总（不定期更新）',
        cate:'1004',
        cateName:'javascript',
        date:'2020-10-08',
        url:'/page/2020/js_question.html'
    },
    {
        title:'.Net MVC + Vue 初体验，MVC视图引入vue组件（不前后端分离）',
        cate:'1005',
        cateName:'VUE',
        date:'2020-10-09',
        url:'/page/2020/netMvcVueTest.html'
    },
    {
        title:'.Net Core使用EF连接数据库的两种方式，CodeFirst & DBFirst',
        cate:'1006',
        cateName:'.Net Core',
        date:'2020-10-16',
        url:'/page/2020/NetCore_DBFirst_CodeFirst.html'
    },
    {
        title:'最近',
        cate:'1001',
        cateName:'杂记',
        date:'2020-12-04',
        url:'/page/2020/20201204.html'
    },
    {
        title:'.Net Core在线预览打印PDF，JsReport的使用',
        cate:'1006',
        cateName:'.Net Core',
        date:'2021-01-27',
        url:'/page/2021/NetCore_Jsreport.html'
    },
    {
        title:'大年三十',
        cate:'1001',
        cateName:'杂记',
        date:'2021-02-11',
        url:'/page/2021/0211.html'
    },
    {
        title:'Linux整理',
        cate:'1007',
        cateName:'Linux',
        date:'2021-02-19',
        url:'/page/2021/Linux.html'
    },
    {
        title:'CentOS 7和CentOS 6的简单比较',
        cate:'1007',
        cateName:'Linux',
        date:'2021-02-22',
        url:'/page/2021/ComparisonOfCentOS7And6.html'
    },
    {
        title:'.Net Core常见的文件下载功能和文件上传功能',
        cate:'1006',
        cateName:'.Net Core',
        date:'2021-05-13',
        url:'/page/2021/NetCoreDownLoad.html'
    },
    {
        title:'git登录验证和一些小问题汇总',
        cate:'1008',
        cateName:'开发工具',
        date:'2021-07-08',
        url:'/page/2021/GitSSH.html'
    },
    {
        title:'mongodb从入门到放弃',
        cate:'1010',
        cateName:'MongoDB',
        date:'2021-07-21',
        url:'/page/2021/mongodb_introduction.html'
    },
    {
        title:'js扁平化数据转换成树结构',
        cate:'1004',
        cateName:'javascript',
        date:'2021-07-22',
        url:'/page/2021/jsArrayToTree.html'
    },
    {
        title:'JavaScript compose、pipe、柯里化、防抖和节流大杂烩',
        cate:'1004',
        cateName:'javascript',
        date:'2021-07-29',
        url:'/page/2021/jsNote.html'
    },
    {
        title:'Video——网页视频的基本样式和基本功能实现',
        cate:'1004',
        cateName:'javascript',
        date:'2021-09-01',
        url:'/page/2021/webVideo_1.html'
    },
    {
        title:'Wpf常见例子实现及演示',
        cate:'1002',
        cateName:'c#',
        date:'2021-09-27',
        url:'/page/2021/wpfCommonDemo.html'
    },
    {
        title:'Wpf实现一个最简单的守护进程',
        cate:'1002',
        cateName:'c#',
        date:'2021-10-25',
        url:'/page/2021/deamonDemo.html'
    },
    {
        title:'window mongodb复制集全量备份与增量备份',
        cate:'1010',
        cateName:'MongoDB',
        date:'2021-11-08',
        url:'/page/2021/mongodump_mongorestore.html'
    },
    {
        title:'C#实现图片/GIF压缩、创建缩略图、添加文本水印、图像水印、解析/创建二维码、条形码功能汇总',
        cate:'1002',
        cateName:'c#',
        date:'2021-11-20',
        url:'/page/2021/ImageToolHelper.html'
    },
    {
        title:'WPF简单的图片/GIF操作工具（ImageTools）演示',
        cate:'1008',
        cateName:'开发工具',
        date:'2021-11-20',
        url:'/page/2021/ImageTools.html'
    },
    {
        title:'一些诗词记录',
        cate:'1001',
        cateName:'杂记',
        date:'2021-11-30',
        url:'/page/2021/favoritePoem.html'
    },
    {
        title:'Win10如何限制某个程序所占用的CPU？',
        cate:'1008',
        cateName:'开发工具',
        date:'2021-12-04',
        url:'/page/2021/limitCPU.html'
    },
    {
        title:'mongodb如何避免长时间停留在 STARTUP2 状态',
        cate:'1010',
        cateName:'MongoDB',
        date:'2021-12-16',
        url:'/page/2021/STARTUP2.html'
    },
    {
        title:'mongodb聚合命令的参考与演示',
        cate:'1010',
        cateName:'MongoDB',
        date:'2022-01-10',
        url:'/page/2022/aggregate.html'
    },
    {
        title:'大年二九除夕夜',
        cate:'1001',
        cateName:'杂记',
        date:'2022-01-31',
        url:'/page/2022/0131.html'
    },
    {
        title:'mongodb聚合管道中常见聚合函数的参考与演示——按顺序排序',
        cate:'1010',
        cateName:'MongoDB',
        date:'2022-05-07',
        url:'/page/2022/aggregation_operator.html'
    },
    {
        title:'mongodb聚合管道中常见聚合函数的参考与演示——按类型分组区分',
        cate:'1010',
        cateName:'MongoDB',
        date:'2022-05-07',
        url:'/page/2022/aggregation_operator_group.html'
    },
    {
        title:'C# for 循环中如何更高效的筛选另一个集合的数据',
        cate:'1002',
        cateName:'c#',
        date:'2022-05-11',
        url:'/page/2022/ImproveFilter.html'
    },
    {
        title:'C#、JS实现解压缩字符串、字符串与Unicode互转',
        cate:'1002',
        cateName:'c#',
        date:'2022-05-27',
        url:'/page/2022/CompressUnicode.html'
    },
    {
        title:'Task.Deley的妙用，简单实现一个请求超时处理',
        cate:'1002',
        cateName:'c#',
        date:'2022-05-28',
        url:'/page/2022/TaskDelay.html'
    },
    {
        title:'简单记录一些Excel的实用操作',
        cate:'1008',
        cateName:'开发工具',
        date:'2022-05-31',
        url:'/page/2022/ExcelAction.html'
    },
    {
        title:'C# 记录一下值类型和引用类型的使用并踩踩坑',
        cate:'1002',
        cateName:'c#',
        date:'2022-06-21',
        url:'/page/2022/refValueType.html'
    },
    {
        title:'MockData.Net使用文档',
        cate:'1002',
        cateName:'c#',
        date:'2022-11-18',
        url:'/page/2022/MockDataNet.html'
    },
    {
        title:'记一次Git乌龙事件——修改线上bug的步骤',
        cate:'1008',
        cateName:'开发工具',
        date:'2022-11-29',
        url:'/page/2022/gitReset.html'
    },
    {
        title:'Redis常用命令合集',
        cate:'1008',
        cateName:'开发工具',
        date:'2022-12-09',
        url:'/page/2022/redisCmdDocs.html'
    },
    {
        title:'2023年三十晚',
        cate:'1001',
        cateName:'杂记',
        date:'2023-01-29',
        url:'/page/2023/2023.html'
    },
    {
        title:'c#各大版本重要变更',
        cate:'1002',
        cateName:'c#',
        date:'2023-01-31',
        url:'/page/2023/CSharpNewFeat.html'
    },
    {
        title:'win10使用docker安装ElasticSearch',
        cate:'1011',
        cateName:'ElasticSearch',
        date:'2023-02-03',
        url:'/page/2023/docker_es.html'
    },
    {
        title:'ElasticSearch 从入门到放弃',
        cate:'1011',
        cateName:'ElasticSearch',
        date:'2023-02-03',
        url:'/page/2023/ESDoc.html'
    }
    ,
    {
        title:'.net core Code First不太常用功能',
        cate:'1006',
        cateName:'.Net Core',
        date:'2023-04-12',
        url:'/page/2023/migration.html'
    },
    {
        title:'Linux-Docker部署.netCore程序',
        cate:'1006',
        cateName:'.Net Core',
        date:'2023-05-16',
        url:'/page/2023/DockerNetCore.html'
    },
    {
        title:'简单记录Sql Server常见锁类型',
        cate:'1013',
        cateName:'Sql',
        date:'2023-08-17',
        url:'/page/2023/SqlserverLock.html'
    },
    {
        title:'简单记录Sql Server事务及隔离级别',
        cate:'1013',
        cateName:'Sql',
        date:'2023-08-31',
        url:'/page/2023/SqlServerIsolation.html'
    },
    {
        title:'01.net开发实用：快速从网址中提取获取域名',
        cate:'1006',
        cateName:'.Net Core',
        date:'2023-11-10',
        url:'/page/2023/GetDomain.html'
    },
    {
        title:'02.net开发实用：c#默认值和可空类型常见的操作',
        cate:'1006',
        cateName:'.Net Core',
        date:'2023-11-21',
        url:'/page/2023/DefaultValue.html'
    },
    {
        title:'SQL Server数据库，如何快速更新数据库表和字段的注释信息',
        cate:'1013',
        cateName:'Sql',
        date:'2024-01-12',
        url:'/page/2024/SetComment.html'
    },
    {
        title:'借助 Mock.js 快速生成数据库虚拟数据',
        cate:'1013',
        cateName:'Sql',
        date:'2024-01-23',
        url:'/page/2024/MockSqlData.html'
    },
    {
        title:'EF CodeFirst迁移错误：Column names in each table must be unique',
        cate:'1006',
        cateName:'.Net Core',
        date:'2024-01-26',
        url:'/page/2024/EFMigrationError.html'
    },
    {
        title:'.Net Core启动程序报错：以一种访问权限不允许的方式做了一个访问套接字的尝试',
        cate:'1006',
        cateName:'.Net Core',
        date:'2024-01-26',
        url:'/page/2024/PortDisable.html'
    },
    {
        title:'2024年三十晚',
        cate:'1001',
        cateName:'杂记',
        date:'2024-03-20',
        url:'/page/2024/2024.html'
    },
    {
        title:'SQL Server数据库的连接操作整理与优化',
        cate:'1013',
        cateName:'Sql',
        date:'2024-03-21',
        url:'/page/2024/SqlJoin.html'
    },
    {
        title:'c#大数据循环的优化',
        cate:'1002',
        cateName:'c#',
        date:'2024-04-01',
        url:'/page/2024/ForQuick.html'
    },
    {
        title:'c#多线程相关整理01——Thread篇',
        cate:'1002',
        cateName:'c#',
        date:'2024-05-09',
        url:'/page/2024/Thread.html'
    },
    {
        title:'c#多线程相关整理02——ThreadPool篇',
        cate:'1002',
        cateName:'c#',
        date:'2024-05-31',
        url:'/page/2024/ThreadPool.html'
    },
    {
        title:'C盘空间不足，清理C盘垃圾文件',
        cate:'1001',
        cateName:'杂记',
        date:'2024-05-31',
        url:'/page/2024/ClearCDisk.html'
    },
    {
        title:'多线程相关整理03——Task篇',
        cate:'1002',
        cateName:'c#',
        date:'2024-06-25',
        url:'/page/2024/Task.html'
    }
    
    
]

